### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by yamatsum** [yamatsum/nvim-web-nonicons#1]

**Comment by yamatsum** [comment]
<img width="1006" alt="Screen Shot 2021-03-11 at 19 06 11" src="https://user-images.githubusercontent.com/42740055/110770803-1c3a6f00-829d-11eb-8b59-aa0a2b135585.png">

**Comment by yamatsum** [comment]
<img width="1006" alt="Screen Shot 2021-03-11 at 18 55 46" src="https://user-images.githubusercontent.com/42740055/110770894-3b390100-829d-11eb-81cb-218c54d32dce.png">

**Comment by yamatsum** [comment]
![Screen Shot 2021-03-11 at 19 23](https://user-images.githubusercontent.com/42740055/110775089-dd5ae800-82a1-11eb-9d95-f9b43a6b616e.png)
![Screen Shot 2021-03-11 at 19 27](https://user-images.githubusercontent.com/42740055/110775090-ddf37e80-82a1-11eb-9b52-75bcd3f9f568.png)
![Screen Shot 2021-03-11 at 19 28](https://user-images.githubusercontent.com/42740055/110775093-de8c1500-82a1-11eb-81ad-321c377aab27.png)
![Screen Shot 2021-03-11 at 19 39 1](https://user-images.githubusercontent.com/42740055/110775095-df24ab80-82a1-11eb-9d96-9cfd32dc4388.png)
![Screen Shot 2021-03-11 at 19 40 1](https://user-images.githubusercontent.com/42740055/110775102-dfbd4200-82a1-11eb-9393-64240026c761.png)

**Comment by yamatsum** [comment]
![Screen Shot 2021-03-12 at 2 34 1](https://user-images.githubusercontent.com/42740055/110829794-dcdf4300-82db-11eb-9650-d905ab468633.png)
![Screen Shot 2021-03-12 at 2 35 1](https://user-images.githubusercontent.com/42740055/110829801-dea90680-82db-11eb-890d-6aa6381c53d1.png)

**Comment by ziulev** [comment]
Hey @yamatsum 
Could you share your configs please
